export * from './base.repository.js'
export * as CampusRepo from './campus.repository.js'
export * as EdificioRepo from './edificio.repository.js'
export * as EmpresaRepo from './empresa.repository.js'
export * as TrabajadorRepo from './trabajador.repository.js'
export * as ServicioRepo from './servicio.repository.js'
export * as TurnoRepo from './turno.repository.js'
export * as AsignacionTurnoRepo from './asignacionTurno.repository.js'
export * as AusenciaRepo from './ausencia.repository.js'
